Added new punctuation rule
avto-dev/markdown-lint pull request #1
Opened 2020-02-13 08:27 UTC by eldario

| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | Yes
## Description

Fixes # (issue)

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made changes in [CHANGELOG.md](https://github.com/avto-dev/markdown-lint/blob/master/CHANGELOG.md) file

2020-02-13 08:31 UTC, tarampampam requested changes

2020-02-13 08:31 UTC, tarampampam commented on lint/rules/changelog.js
> +            if ((/[,.;:]\s/mi.test(token.line)) === false) {
После точки и конце предложения тоже? Это противоречит другому правилу, что запрещает пробелы после знаков пунктуации

2020-02-14 18:05 UTC, tarampampam requested changes

2020-02-14 18:05 UTC, tarampampam commented on tests/samples/changelog/incorrect/delimiter-with-spaces.md
> +- Dont touch filenames in code tags `file/leaves.here` like .this
На каждый "не валидный" кейс надо создавать отдельный файл-копию от валидного, так как тест проверяет что "что то упало с таким сообщением", но не каждый описанный "ошибочный" пример использования

2020-02-14 18:05 UTC, tarampampam commented on lint/rules/changelog.js
> +            // Remove tags <code>, <i> and <b>
Опасно.. Ты любишь рисковать!

2020-02-14 18:05 UTC, tarampampam commented on lint/rules/changelog.js
> +            // Remove tags <code>, <i> and <b>
Нужен мануальный тест на существующих "старых" файлах, покажешь что нет ложных срабатываний лично?

2020-02-17 17:22 UTC, eldario commented on tests/samples/changelog/incorrect/delimiter-with-spaces.md
> +- Dont touch filenames in code tags `file/leaves.here` like .this
Добавил ошибночные проверки, но с регулярками, что-то нужно сделать

2020-02-17 17:23 UTC, eldario commented on lint/rules/changelog.js
> +            // Remove tags <code>, <i> and <b>
Здесь не **remove**, а **replace**. Но замена происходит аккуратно

2020-02-17 17:24 UTC, eldario commented on lint/rules/changelog.js
> +            if ((/[,.;:]\s/mi.test(token.line)) === false) {
Какое правило запрещает пробел после знака пунктуации (речь не про конец строки)?

2020-03-31 04:46 UTC, tarampampam commented
Решение выглядит довольно рискованным, велика вероятность ложно-положительных срабатываний. Пока что закрою этот MR (возможно вернемся к нему позже).

Спасибо за проделанную работу!

2020-03-31 04:46 UTC, closed without merging